### ISSUE TITLE
Question: use on an already formatted external hard drive

### ISSUE THREAD

**Issue by mesqueeb** [edenwaith/Permanent-Eraser#11]
I have external hard drives I want to get rid of. I have already formatted them via macOS disk utility.
However, I'm a bit scared about data recovery if I sell them or throw them out.

Can I use Permanent-Eraser on these already re-formatted external hard drives?

Best regards

**Comment by edenwaith** [comment]
@mesqueeb Yes, you can use Permanent Eraser on a hard drive that was already formatted.  PE is generally used to overwrite an existing file.  Disk Utility can also be used to erase and format hard drives as well, especially if the higher security settings were used.
