### ISSUE TITLE
Permanent Eraser 2.9.1 not working on macOS Ventura 13.0 Beta 8 (22A5352e) after update

### ISSUE THREAD

**Issue by MrCrispyBacon** [edenwaith/Permanent-Eraser#12]
Hi, Permanent Eraser 2.9.1 stopped working on macOS Ventura 13.0 Beta 8 (22A5352e).. this app was working fine till Ventura beta 7 

After the uninstall and reinstall Permanent Eraser 2.9.1...the files in the trash won't be deleted

Thanks in advance and hope you can find a solution coz this app is great and working with it for many years everyday

**Comment by edenwaith** [comment]
@MrCrispyBacon Thank you for this head's up.  Once the full version of macOS Ventura is out, I will verify any issues that Permanent Eraser is having with that version of macOS.

**Comment by edenwaith** [comment]
@MrCrispyBacon I tested Permanent Eraser 2.9.1 with the final version of macOS Ventura (13.0) and encountered no issues with deleting files from the trash or individually.  I'm hoping what you encountered was just an issue with Beta 8.  If you can reproduce this issue on the final version of Ventura, please let me know with reproducible steps.

**Comment by MrCrispyBacon** [comment]
Hi there…Im on final release and it bugged 3 times today….I had to move the files that I wanted to delete from the trash to the desktop and move it again to trash to delete it with PE….its being doing this occasionally…I uninstall and installed PE a few times
Anyways Ill leet you know if it continues to bug
Thanks and keep up the good work!
